### ISSUE TITLE
Left and Right one time

### ISSUE THREAD

**Issue by AndreyBespamyatnov** [Baseflow/Xamarin-Sidebar#17]
How a can add left and rigth menu at  one time?

**Comment by jdehlin** [comment]
That isn't currently an option. It might be possible to implement that without introducing breaking changes. I can look into it.

**Comment by jdehlin** [comment]
Looking more into this it would basically require rebuilding the component from scratch. This is not something I'm going to pursue for the time being but I'll keep it in mind for the future.
