### ISSUE TITLE
Problem with X alignment

### ISSUE THREAD

**Issue by xplatsolutions** [Baseflow/Xamarin-Sidebar#19]
I have used it with XIBs exactly as your example but I get misplace the X alignment even for the navigation bar. See screenshot.

I use auto layout and size classes. But it doesn't make a difference if I turn it off.

Any thoughts?
![ios simulator screen shot feb 20 2015 23 24 32](https://cloud.githubusercontent.com/assets/10971321/6312839/a7435e42-b957-11e4-8f99-28ca16fbcce2.png)

**Comment by jdehlin** [comment]
In my examples I don't use the XIBs, I use code to build my views. Without seeing your code I'm not sure what the alignment issue is. What virtual device did you take that screenshot in? iPhone 5?

**Comment by xplatsolutions** [comment]
iPhone 6 Simulator.

I haven't done anything different from the sample code that you have on readme than just using Xibs.
