### ISSUE TITLE
System.MissingMethodException at RootViewController.cs

### ISSUE THREAD

**Issue by charlesbock** [Baseflow/Xamarin-Sidebar#22]
Hi,

The Unified sample project works but when I copied all the files from sample by one by one into my project and implemented it the same way as is in the sample project it throws an exception at **RootViewController.cs:ViewDidLoad**

in line:
`SidebarController = new SidebarNavigation.SidebarController(this, NavController, new SideMenuController());`

This is the exception:
`System.MissingMethodException: Method not found: 'UIKit.UIGestureRecognizer.set_Delegate'.
  at SidebarNavigation.SidebarController.Initialize (UIKit.UIViewController currentViewController, UIKit.UIViewController navigationViewController) [0x00000] in <filename unknown>:0
  at SidebarNavigation.SidebarController..ctor (UIKit.UIViewController rootViewController, UIKit.UIViewController contentAreaController, UIKit.UIViewController navigationAreaController) [0x00000] in <filename unknown>:0`

**Comment by jdehlin** [comment]
I'm sorry the library is giving you trouble. I just went through the process of creating a new Unified API iPhone project, installing the component from the component store, and implementing the controllers similar to what's in the Navigation Unified Sample. I wasn't able to reproduce the exception you're getting. Did you add this library to your project by installing the component? If so are you sure you installed the latest version? Version 1.5 had this bug.

I would love to help you resolve this issue. Any additional details you can provide are appreciated.

**Comment by sudesh1456** [comment]
I've same error on same line. 
Please help.
I've latest version

**Comment by jdehlin** [comment]
Did you add this library to your project by installing the component?
