### ISSUE TITLE
Temporarily disable sidebar

### ISSUE THREAD

**Issue by picotrain1** [Baseflow/Xamarin-Sidebar#26]
Hi,

I'm currently using the Sidebar successfully.  I followed your easy to use example of StoryBoardSideBar.  However, in my app it checks to see if the user is still logged in and if not the navigation controller will push a custom login view controller over whatever controller is currently shown.  The login screen shows successfully, but the sidebar menu is still accessible by swiping the screen.  The user can then bypass the login and continue.

Is there a way to temporarily disable the sidebar while the login screen is open?  If not a temporary fix, is there a way to remove the sidebar while showing the login screen and then create the sidebar again once the user has successfully logged in?

**Comment by jdehlin** [comment]
I apologize for the delay. In my applications I've generally presented a login controller that is not within a sidebar controller. Once the user is logged in then I'll replace the login controller with the sidebar controller. The ability to disable the sidebar is a good idea, though. I'm working on that feature now and it should be in the codebase today and in the Component Store within a few days.

**Comment by picotrain1** [comment]
Hi, our apps have a timeout period which will force the user back to the login screen on any given page of the app which is why it's necessary to disable the sidebar at any given time.

The code changes work great.  Thanks for your hard work!
