### ISSUE TITLE
Customize gesture starting touch area

### ISSUE THREAD

**Issue by DeadDogDeus** [Baseflow/Xamarin-Sidebar#32]
Hi,
It is really good sidebar for Xamarin but I want to change starting touch area form 50 to another value,
Could you customise your control?
I have found next code in your sources, you can change 50 to some property, it will be enough as I think.

if (MenuLocation == MenuLocations.Left)
    _ignorePan = _panGesture.LocationInView(view).X > 50;
else
    _ignorePan = _panGesture.LocationInView(view).X < view.Bounds.Width - 50;

**Comment by DeadDogDeus** [comment]
Could you help me? You have updated your project but this changes still are not available via Xamarin components.

**Comment by jdehlin** [comment]
It takes some time for changes to be approved by Xamarin. It should be up
in the component store in a couple of days.

Jack

**Comment by DeadDogDeus** [comment]
Oh, Thanks. I close this issue.
