### ISSUE TITLE
Need help with sidebar menu.

### ISSUE THREAD

**Issue by ghost** [Baseflow/Xamarin-Sidebar#34]
Hi i'm currently trying to use the sidebar menu with my project but i cannot get it to work correctly work how i need to.

what im trying to do is have it so when u click to open the sidemenu it shows a list on static tableview cells and on a cell click open to a new view/table view.
in xamarin you need a navigation controller to be the initial view controller in order to get it to work correctly (as seem in pic below)   Is there anyway around this or a fix for the sidebar?
![image](https://cloud.githubusercontent.com/assets/14005528/9532544/e94aba3e-4cd1-11e5-896d-bcaa2479334d.png)

**Comment by jdehlin** [comment]
I have a method for changing the content view but not the menu view. That's something I can add, but I'm not sure when I'll be able to get to it. Hopefully within a few days.

**Comment by jdehlin** [comment]
This is now available. I'll be deploying it to the component store at some point. For now you can grab it from here though.
