### ISSUE TITLE
Publish Xamarin-Sidebar as Nuget package

### ISSUE THREAD

**Issue by martijn00** [Baseflow/Xamarin-Sidebar#36]

**Comment by martijn00** [comment]
Hi,

Are you considering this? Is there anything i can do to help?

**Comment by corliss** [comment]
Agree, this would be quite useful.

**Comment by martijn00** [comment]
This is up on Nuget: https://www.nuget.org/packages/SidebarNavigation/

**Comment by jdehlin** [comment]
Nice!
