### ISSUE TITLE
Animations are very slow in iPhone Simulator

### ISSUE THREAD

**Issue by j0nscalet** [Baseflow/Xamarin-Sidebar#38]
Kick ass job on the control, great work jdehlin.

It works fine on a device however when running in the simulator the presence of the sidebar controller makes all transitions and animations very slow. For example when calling:
SidebarController.ChangeContentView(viewcontroller);

The animation/transition executes but very slowly. Again, deployed on a device everything works perfectly.

I am planning on digging into the animations but first wanted to see if someone else has experienced this.

Thanks so much.
Jon

**Comment by j0nscalet** [comment]
Okay, I'm insanely stupid.

Debug -> Slow Animations (is on).

Now it's off. Sorry! :(

Thanks again for the hard work on Xamarin-Sidebar. I love how the menuViewController is flexible enough for any type of control. Makes it easy to create a menu that's more than just a tableView.

**Comment by jdehlin** [comment]
Glad you got it figured out. Glad you like it. Having flexibility in the menu view was my main driver for building it.
