### ISSUE TITLE
Multiple storyboards

### ISSUE THREAD

**Issue by conrad90909** [Baseflow/Xamarin-Sidebar#49]
Hi, Firstly, fantastic control, love it and got it working really easily, however we have decided to implement it throughout our application instead of just on the home screen and I am having issues with a setup of multiple storyboards, will this sidebar work for me?  The errors I am receiving are when a segue to a different storyboard to main occurs.

Many thanks.

Conrad

**Comment by conrad90909** [comment]
Apologies, I have managed to get this working, please close :+1:

**Comment by jdehlin** [comment]
Glad you were able to get it working.
