### ISSUE TITLE
Unable to rearrange UITableView items when the contentController contains a UITableView  

### ISSUE THREAD

**Issue by delaney31** [Baseflow/Xamarin-Sidebar#68]
Hi
I'm trying to load my own viewController which contains a UITableView with the ability to delete and rearrange  items, but when i use the NavigationUnifiedSample example code with a rootViewController i can no longer rearrange my tableview items. I've recreated the problem using your code by and adding my viewController.

Thanks for your help
Tim
[NavigationUnifiedSample.zip](https://github.com/jdehlin/Xamarin-Sidebar/files/636807/NavigationUnifiedSample.zip)

**Comment by jdehlin** [comment]
Did you figure out the problem?

**Comment by delaney31** [comment]
I just saw the work around for this by @kinex... This worked for me!

**Comment by alexshikov** [comment]
@delaney31 I'm facing the same issue. Could you please explain or send a reference to the workaround?

**Comment by alexshikov** [comment]
Answering my question:
- reference https://github.com/jdehlin/Xamarin-Sidebar/issues/48#issuecomment-253916386
- explanation: `disable pan gesture`
